name: Deploy Server

on:
  push:
    branches:
      - main

jobs:
  deploy-to-server:
    steps:
      - name: Build docker image
        run: |
          docker build -t hostium-backend:${{ github.sha }} .

      - name: Save docker image as tar
        run: |
          docker save hostium-backend:${{ github.sha }} -o hostium-backend.tar
          chmod 644 demo-server.tar

      - name: Copy docker image to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          source: hostium-backend.tar
          target: ~/images

      - name: Load the docker image run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            docker load -i /root/images/hostium-backend.tar
            docker rm -f hostium-backend
            docker run -d -p 8000:8000 --name hostium-backend hostium-backend:${{ github.sha }}
