version: "3.8"

services:
  app:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}" # Maps PORT to the container's PORT (default 8000)
    env_file:
      - .env # Loads environment variables from the .env file
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
    environment:
      - PORT=${PORT} # Optional, this can be removed if already in .env
      - MONGO_URI=${MONGO_URI}
      - TOKEN_EXPIRY=${TOKEN_EXPIRY}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - CLIENT_URL=${CLIENT_URL}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - SESSION_SECRET=${SESSION_SECRET}
